version: '3.7'
services:
    bridge:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "4200:4200"
        volumes:
            - ".:/app"
            - "/app/node_modules"
        