import { AppliedJob } from 'app/class';

export const fakeAppliedJobs: AppliedJob[] = [
  {
    title: 'Software Engineer I',
    company: 'Google',
    imageSource: 'assets/logos/google-logo.png',
    description: '',
    progress: 0.25,
    dateApplied: new Date(),
    dateUpdated: new Date(),
  },
  {
    title: 'Software Engineer I',
    company: 'Youtube',
    imageSource: 'assets/logos/youtube-logo.png',
    description: '',
    progress: 0.75,
    dateApplied: new Date(),
    dateUpdated: new Date(),
  },
  {
    title: 'Software Engineer I',
    company: 'Nvidia',
    imageSource: 'assets/logos/nvidia-logo.png',
    description: '',
    progress: 0.50,
    dateApplied: new Date(),
    dateUpdated: new Date(),
  },
  {
    title: 'DevOps Engineer',
    company: 'Nvidia',
    imageSource: 'assets/logos/nvidia-logo.png',
    description: '',
    progress: 0.25,
    dateApplied: new Date(),
    dateUpdated: new Date(),
  },
  {
    title: 'Data Engineer',
    company: 'Facebook',
    description: '',
    imageSource: 'assets/logos/facebook-logo.png',
    progress: 0.50,
    dateApplied: new Date(),
    dateUpdated: new Date(),
  },
  {
    title: 'Data Engineer',
    company: 'Facebook',
    description: '',
    imageSource: 'assets/logos/facebook-logo.png',
    progress: 1,
    dateApplied: new Date(),
    dateUpdated: new Date(),
  },
  {
    title: 'Senior Backend Engineer',
    company: 'Netflix',
    description: '',
    imageSource: 'assets/logos/netflix-logo.png',
    progress: 0,
    dateApplied: new Date(),
    dateUpdated: new Date(),
  },
  {
    title: 'Project Manager',
    company: 'Netflix',
    description: '',
    imageSource: 'assets/logos/netflix-logo.png',
    progress: -1,
    dateApplied: new Date(),
    dateUpdated: new Date(),
  },
];
